/* 
*  Copyright (c) 2019. All right reserved
 * Created on 2022-01-05 ( Date ISO 2022-01-05 - Time 16:10:40 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
 * Created on 2022-01-05 ( 16:10:40 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */

package com.maan.crm.bean;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

/**
 * Domain class for entity "BranchMaster"
 *
 * @author Telosys Tools Generator
 *
 */
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Entity
@DynamicInsert
@DynamicUpdate
@Builder
@Table(name = "AGENT_MASTER")

public class AgentMaster implements Serializable {

	private static final long serialVersionUID = 1L;

	// --- ENTITY DATA FIELDS

	@Id
	@Column(name = "AGENT_CODE", length = 20)
	private String agentCode;
	
	@Column(name = "COMPANY_ID", length = 20)
	private String companyId;

	@Column(name =  "SNO")
	private Integer sno;

	@Column(name = "AGENT_NAME",  length = 20)
	private String agentName;

	@Column(name = "ORAGENT_CODE", length = 75)
	private String oragentCode;

	@Temporal(TemporalType.DATE)
	@Column(name = "CREATED_DATE")
	private Date createdDate;

	@Column(name = "MOBILE_NO", length =10)
	private String mobileNo;

	@Column(name = "IRDA_APPROVED", length = 75)
	private String irdaApproved;

	@Column(name = "IRDA_LICENSE_NO", length = 15)
	private String irdaLicenseNo;

	@Column(name = "EMAIL", length = 40)
	private String email;

	@Column(name = "STATUS", length = 1)
	private String status;

	@Column(name = "BRANCH_CODE", length = 40)
	private String branchCode;

	@Column(name = "REGION", length = 50)
	private String region;

	@Column(name = "CHANNEL", length = 50)
	private String channel;

	@Column(name = "CLIENT_CODE", length = 40)
	private String clientCode;
	
	@Temporal(TemporalType.DATE)
	@Column(name = "ENTRY_DATE")
	private Date entryDate;
	
	@Temporal(TemporalType.DATE)
	@Column(name = "EXPIRY_DATE")
	private Date expiryDate;

	@Temporal(TemporalType.DATE)
	@Column(name = "LICENCE_EXPIRY_DATE")
	private Date licenceExpiryDate;
	
	@Column(name = "REMARKS", length = 100)
	private String remarks;

}
