/* 
*  Copyright (c) 2019. All right reserved
 * Created on 2022-01-05 ( Date ISO 2022-01-05 - Time 16:10:40 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
 * Created on 2022-01-05 ( 16:10:40 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */

package com.maan.crm.bean;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

/**
 * Domain class for entity "BranchMaster"
 *
 * @author Telosys Tools Generator
 *
 */
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Entity
@DynamicInsert
@DynamicUpdate
@Builder
@IdClass(CampaignTemplateId.class)
@Table(name = "CAMPAIGN_TEMPLATE")

public class CampaignTemplate implements Serializable {

	private static final long serialVersionUID = 1L;

// --- ENTITY PRIMARY KEY
	@Id
	@Column(name = "FIELD_ID", nullable = false)
	private Integer fieldId;



// --- ENTITY DATA FIELDS
	@Column(name = "FIELD_NAME", length = 100)
	private String fieldName;

	@Column(name = "ORDER_ID", length = 100)
	private String orderId;


	@Column(name = "STATUS", length = 1)
	private String status;

	@Temporal(TemporalType.DATE)
	@Column(name = "ENTRY_DATE")
	private Date entryDate;

}
