/*
 * Created on 2022-01-05 ( 16:10:40 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.maan.crm.bean;

import java.io.Serializable;

import lombok.Getter;
import lombok.Setter;

/**
 * Composite primary key for entity "BranchMaster" ( stored in table
 * "BRANCH_MASTER" )
 *
 * @author Telosys
 *
 */

@Getter
@Setter
public class CompanyTypeMasterId implements Serializable {

	private static final long serialVersionUID = 1L;

	private Integer sNo;

	private String insCompanyId;

}
