/* 
*  Copyright (c) 2019. All right reserved
 * Created on 2022-05-14 ( Date ISO 2022-05-14 - Time 15:00:24 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
 * Created on 2022-05-14 ( 15:00:24 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */

package com.maan.crm.bean;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

import com.fasterxml.jackson.annotation.JsonFormat;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

/**
 * Domain class for entity "ClaimLoginUserDetails"
 *
 * @author Telosys Tools Generator
 *
 */
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Entity
@DynamicInsert
@DynamicUpdate
@Builder
@IdClass(DocumentTypeDetailsId.class)
@Table(name = "DOCUMENT_TYPE_MASTER")

public class DocumentTypeDetails implements Serializable {

	private static final long serialVersionUID = 1L;

	// --- ENTITY PRIMARY KEY
	@Id
	@Column(name = "DOC_SEQ_ID", nullable = false)
	private Integer docSeqId;

	@Id
	@Column(name = "REF_NO", nullable = false)
	private String refNo;

	@Id
	@Column(name = "DOC_STATUS_CODE")
	private Date docStatusCode;


	// --- ENTITY DATA FIELDS
	@Column(name = "DOC_STATUS_DESC")
	private String docStatusDesc;

	@Column(name = "DOC_APPLICABLE_ID")
	private Integer docApplciableId;

	@Column(name = "DOC_APPLICABLE", length = 100)
	private String docApplciable;

	@Column(name = "DOCUMENT_ID", length = 300)
	private Integer documentId;
	
	@Column(name = "DOCUMENT_DESC", length = 300)
	private String documentDesc ;
	
	@Temporal(TemporalType.DATE)
	@Column(name = "ENTRY_DATE")
	private Date entryDate;
	
	@Column(name = "STATUS", length = 300)
	private String status;

}
