/* 
*  Copyright (c) 2019. All right reserved
 * Created on 2022-05-14 ( Date ISO 2022-05-14 - Time 15:00:24 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
 * Created on 2022-05-14 ( 15:00:24 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */

package com.maan.crm.bean;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

import com.fasterxml.jackson.annotation.JsonFormat;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

/**
 * Domain class for entity "ClaimLoginUserDetails"
 *
 * @author Telosys Tools Generator
 *
 */
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Entity
@DynamicInsert
@DynamicUpdate
@Builder
@IdClass(PolicyDetailsId.class)
@Table(name = "POLICY_DETAILS")

public class PolicyDetails implements Serializable {

	private static final long serialVersionUID = 1L;

	// --- ENTITY PRIMARY KEY
	@Id
	@Column(name = "POLICYID", nullable = false)
	private Integer policyid;

	@Id
	@Column(name = "POLICY_NUMBER")
	private String policyNumber;

	@Id
	@Column(name = "INS_COMPANY_ID")
	private String insCompanyId;

	@Id
	@Column(name = "BRANCH_CODE")
	private String branchCode;

	@Id
	@Column(name = "LEAD_ID", nullable = false)
	private String leadId;

	@Id
	@Column(name = "CLIENTREFNO")
	private String clientRefNo;

	@Column(name = "PROSPECTID")
	private Integer prospectId;

	@Column(name = "BUSINESSTYPE")
	private String businessType;

	@Column(name = "BUSINESSTYPEID")
	private Integer businessTypeId;

	@Column(name = "CLASSS")
	private String classs;

	@Column(name = "CLASSID")
	private Integer classId;

	@Column(name = "POLICYTYPE")
	private String policyType;

	@Column(name = "POLICYTYPEID")
	private Integer policyTypeId;

	@Column(name = "INSURER")
	private String insurer;

	@Column(name = "INSURERID")
	private Integer insurerId;

	@Column(name = "INSURERBRANCH")
	private String insurerBranch;

	@Column(name = "INSURERBRANCHID")
	private Integer insurerBranchId;

	@Column(name = "INSURANCEPLAN")
	private String insurancePlan;

	@Column(name = "COINSURERDETAILS")
	private String coInsurerDetails;

	@Column(name = "VEHICLEID")
	private Integer vehicleId;

	@Column(name = "CLIENTID")
	private Integer clientId;

	@Column(name = "COVERNOTENUMBER")
	private String coverNoteNumber;

	@Temporal(TemporalType.DATE)
	@JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "dd/MM/yyyy", locale = "en-IN", timezone = "Asia/Calcutta")
	@Column(name = "STARTDATE")
	private Date startDate;

	@Temporal(TemporalType.DATE)
	@JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "dd/MM/yyyy", locale = "en-IN", timezone = "Asia/Calcutta")
	@Column(name = "EXPIRYDATE")
	private Date expiryDate;

	@Temporal(TemporalType.DATE)
	@JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "dd/MM/yyyy", locale = "en-IN", timezone = "Asia/Calcutta")
	@Column(name = "NEXTPREMIUMDUEDATE")
	private Date nextPremiumDueDate;

	@Column(name = "RENEWABLEFLAGYN")
	private String renewableFlagYN;

	@Column(name = "SUMINSURED")
	private Double sumInsured;

	@Column(name = "DISCOUNTPERCENTAGE")
	private Double discountPercentage;

	@Column(name = "NOCLAIMBONUS")
	private Double noClaimBonus;

	@Column(name = "COMMISSION_BASE_PREMIUM", nullable = false)
	private Double commissionBasePremium;

	@Column(name = "OTHERPREMIUM")
	private Double otherPremium;

	@Column(name = "TOTALPREMIUM")
	private Double totalPremium;

	@Column(name = "GST")
	private Double gST;

	@Column(name = "PREMIUMWITHGST")
	private Double premiumWithGST;

	@Temporal(TemporalType.DATE)
	@JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "dd/MM/yyyy", locale = "en-IN", timezone = "Asia/Calcutta")
	@Column(name = "COMMENCEMENTDATE")
	private Date commencementDate;

	@Column(name = "POLICYTERMINYEARS")
	private Integer policyTermInYears;

	@Column(name = "PREMIUMPAYINGTERMINYEARS")
	private Integer premiumPayingTermInYears;

	@Column(name = "AUTODEBITYN")
	private String autoDebitYN;

	@Column(name = "PREMIUMPAYMENTTYPE")
	private String premiumPaymentType;

	@Column(name = "PREMIUMPAYMENTTYPEID")
	private Integer premiumPaymentTypeId;

	@Column(name = "PREMIUMPAYMENTFREQUENCY")
	private String premiumPaymentFrequency;

	@Column(name = "PREMIUMPAYMENTFREQUENCYID")
	private Integer premiumPaymentFrequencyId;

	@Temporal(TemporalType.DATE)
	@JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "dd/MM/yyyy", locale = "en-IN", timezone = "Asia/Calcutta")
	@Column(name = "PREMIUMDUEDATE")
	private Date premiumDueDate;

	@Temporal(TemporalType.DATE)
	@JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "dd/MM/yyyy", locale = "en-IN", timezone = "Asia/Calcutta")
	@Column(name = "MATURITYDATE")
	private Date maturityDate;

	@Temporal(TemporalType.TIMESTAMP)
	//@JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "dd/MM/yyyy", locale = "en-IN", timezone = "Asia/Calcutta")
	@Column(name = "Entry_Date")
	private Date entryDate;

	@Column(name = "Status", length = 10)
	private String status;

	@Column(name = "CREATEDBY", length = 100)
	private String createdBy;

	@Column(name = "STATUSS", length = 10)
	private String statuss;

	@Column(name = "STATUS_DESCRIPTION", length = 10)
	private String statusDescription;

	@Column(name = "ENQUIRY_ID", length = 20)
	private String enquiryId;

	@Column(name = "QUOTE_NO")
	private Integer quoteNo;

}
