/* 
*  Copyright (c) 2019. All right reserved
 * Created on 2022-05-14 ( Date ISO 2022-05-14 - Time 15:00:24 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
 * Created on 2022-05-14 ( 15:00:24 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */

package com.maan.crm.bean;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

import com.fasterxml.jackson.annotation.JsonFormat;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

/**
 * Domain class for entity "ClaimLoginUserDetails"
 *
 * @author Telosys Tools Generator
 *
 */
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Entity
@DynamicInsert
@DynamicUpdate
@Builder
@IdClass(ProspectOldPolicyDetailsId.class)
@Table(name = "PROSPECT_OLD_POLICY_DETAILS")

public class ProspectOldPolicyDetails implements Serializable {

	private static final long serialVersionUID = 1L;

	// --- ENTITY PRIMARY KEY
	@Id
	@Column(name = "PROSPECTID", nullable = false)
	private Integer prospectId;

	@Id
	@Column(name = "OLDPOLICYID", nullable = false)
	private Integer oldPolicyId;
	
	@Column(name = "OLDPOLICYNO")
	private String OldPolicyNo;

	@Column(name = "OLDINSURER")
	private String OldInsurer;
	
	@Column(name = "OLDINSURERID")
	private Integer OldInsurerId;
	
	@Column(name = "OLDINSURANCEPLAN")
	private String OldInsurancePlan;
	
	@Column(name = "OLDPOS")
	private String OldPOS;
	
	@Column(name = "OLDPOSID")
	private Integer OldPOSId;
	
	@Column(name = "OLDSOURCE")
	private String OldSource;
	
	@Column(name = "OLDSOURCEID")
	private Integer OldSourceId;
	
	@Temporal(TemporalType.DATE)
	@JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "dd/MM/yyyy", locale = "en-IN", timezone = "Asia/Calcutta")
	@Column(name = "OLDSTARTDATE")
	private Date OldStartDate;
	
	@Temporal(TemporalType.DATE)
	@JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "dd/MM/yyyy", locale = "en-IN", timezone = "Asia/Calcutta")
	@Column(name = "OLDEXPIRYDATE")
	private Date OldExpiryDate;
	
	@Column(name = "ANYCLAIMLASTYEAR")
	private String AnyClaimLastYear;
	
	@Column(name = "ANYCLAIMLASTYEARID")
	private Integer AnyClaimLastYearId;
	
	@Column(name = "VEHICLETRANSFERCASE")
	private String VehicleTransferCase;
	
	@Column(name = "VEHICLETRANSFERCASEID")
	private Integer VehicleTransferCaseId;
	
	@Column(name = "OLDIDV")
	private String OldIDV;
	
	@Column(name = "OLDPOLICYTERM")
	private String OldPolicyTerm;
	
	@Column(name = "OLDELECTRONICACCESSORYVALUE")
	private String OldElectronicAccessoryValue;
	
	@Column(name = "OLDNONELECTRONICACCESSORYVALUE")
	private String OldNonElectronicAccessoryValue;
	
	@Column(name = "OLDSUMINSURED")
	private double OldSumInsured;
	
	@Column(name = "OLDNOCLAIMBONUS")
	private double OldNoClaimBonus;
	
	@Column(name = "OLDDISCOUNTPERCENTAGE")
	private double OldDiscountPercentage;
	
	@Column(name = "OLDOWNDAMAGEPREMIUM")
	private double OldOwnDamagePremium;
	
	@Column(name = "OLDADDONPREMIUM")
	private double OldAddOnPremium;
	
	@Column(name = "OLDODADDONCOMMISSIONBASEPREMIUM")
	private double OldODAddOnCommissionBasePremium;
	
	@Column(name = "OLDTHIRDPARTYLIABILITYPREMIUM")
	private double OldThirdPartyLiabilityPremium;
	
	@Column(name = "OLDTOTALPREMIUM")
	private double OldTotalPremium;
	
	@Column(name = "OLDGST")
	private double OldGST;
	
	@Column(name = "OLDTOTALPREMIUMWITHGST")
	private double OldTotalPremiumwithGST;
	
	@Column(name = "OLDPOLICYADDITIONALINFORMATION") 
	private double OldPolicyAdditionalInformation;
	
}
