/* 
*  Copyright (c) 2019. All right reserved
 * Created on 2022-05-14 ( Date ISO 2022-05-14 - Time 15:00:24 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
 * Created on 2022-05-14 ( 15:00:24 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */

package com.maan.crm.bean;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

import com.fasterxml.jackson.annotation.JsonFormat;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

/**
 * Domain class for entity "ClaimLoginUserDetails"
 *
 * @author Telosys Tools Generator
 *
 */
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Entity
@DynamicInsert
@DynamicUpdate
@Builder
@IdClass(ProspectsQuotationOtherDetailsId.class)
@Table(name = "PROSPECTS_QUOTATION_OTHER_DETAILS")

public class ProspectsQuotationOtherDetails implements Serializable {

	private static final long serialVersionUID = 1L;

	// --- ENTITY PRIMARY KEY
	@Id
	@Column(name = "PROSPECTID", nullable = false)
	private int prospectId;

	@Id
	@Column(name = "OTHERDETAILSID", nullable = false)
	private int otherDetailsId;

	@Column(name = "POLICYADDITIONALINFORMATION")
	private String policyAdditionalInformation;

	@Column(name = "ISSUEDBYUSER")
	private String issuedByUser;

	@Column(name = "RENEWALNOTICEFLAGYN")
	private String renewalNoticeFlagYN;

	@Column(name = "RECOMMENDEDFLAGYN")
	private String recommendedFlagYN;

	@Temporal(TemporalType.DATE)
	@JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "dd/MM/yyyy", locale = "en-IN", timezone = "Asia/Calcutta")
	@Column(name = "ISSUEDATE")
	private Date issueDate;
}
