/* 
*  Copyright (c) 2019. All right reserved
 * Created on 2022-05-14 ( Date ISO 2022-05-14 - Time 15:00:24 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
 * Created on 2022-05-14 ( 15:00:24 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */

package com.maan.crm.bean;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.Table;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

/**
 * Domain class for entity "ClaimLoginUserDetails"
 *
 * @author Telosys Tools Generator
 *
 */
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Entity
@DynamicInsert
@DynamicUpdate
@Builder
@IdClass(ProspectQuotationPolicyAccountsId.class)
@Table(name = "PROSPECT_QUOTATION_POLICY_ACCOUNTS")

public class ProspectQuotationPolicyAccounts implements Serializable {

	private static final long serialVersionUID = 1L;

	// --- ENTITY PRIMARY KEY
	@Id
	@Column(name = "POLICY_ACCID", nullable = false)
	private Integer policyAccId;

	@Id
	@Column(name = "PROSPECTID", nullable = false)
	private Integer prospectId;

	@Column(name = "SUMINSURED")
	private double sumInsured;

	@Column(name = "OWNDAMAGEPREMIUM")
	private double ownDamagePremium;

	@Column(name = "DISCOUNTPERCENTAGE")
	private double discountPercentage;

	@Column(name = "NOCLAIMBONUS")
	private double noClaimBonus;

	@Column(name = "TOTALOWNDAMAGEPREMIUMA")
	private double totalOwnDamagePremiumA;

	@Column(name = "TOTALADDONCOVERPREMIUMB")
	private double totalAddOnCoverPremiumB;

	@Column(name = "ODADDONCOMMISSIONBASEPREMIUMAB")
	private double oDAddOnCommissionBasePremiumAB;

	@Column(name = "BASICTP")
	private double basicTP;

	@Column(name = "OWNERDRIVERPAYN")
	private String ownerDriverPAYN;

	@Column(name = "BIFUELKITYN")
	private String bifuelkitYN;

	@Column(name = "GEOGRAPHICALAREAYN")
	private String geographicalAreaYN;

	@Column(name = "OWNERDRIVERPA")
	private double ownerDriverPA;

	@Column(name = "BIFUELKIT")
	private double bifuelkit;

	@Column(name = "GEOGRAPHICALAREA")
	private double geographicalArea;

	@Column(name = "UNNAMEDPASSENGERPAYN")
	private double unnamedPassengerPAYN;

	@Column(name = "UNNAMEDPASSENGERPA")
	private double unnamedPassengerPA;

	@Column(name = "UNNAMEDPASSENGERLIMITPERPERSON")
	private double unnamedPassengerLimitPerPerson;

	@Column(name = "UNNAMEDPASSENGERNOOFSEATS")
	private Integer unnamedPassengerNoofSeats;

	@Column(name = "LLTOPAIDDRVEMP")
	private double lLtoPaidDrvEmp;

	@Column(name = "LLTOPAIDDRVEMPYN")
	private String lLtoPaidDrvEmpYN;

	@Column(name = "NOOFDRVEMP")
	private Integer noofDrvEmp;

	@Column(name = "TOTALLIABILITYPREMIUMC")
	private double totalLiabilityPremiumC;

	@Column(name = "TOTALPREMIUMABC")
	private double totalPremiumABC;

	@Column(name = "GST")
	private double gST;

	@Column(name = "PREMIUMWITHGST")
	private double premiumwithGST;

	@Column(name = "OTHERPREMIUM")
	private double otherPremium;

	@Column(name = "COMMISSIONBASEPREMIUM")
	private double commissionBasePremium;

	@Column(name = "PAPAIDDRV")
	private double pAPaidDrv;

	@Column(name = "PAPAIDDRVYN")
	private String pAPaidDrvYN;

	@Column(name = "PAPAIDDRVNOOFSEATS")
	private Integer pAPaidDrvNoofSeats;

	@Column(name = "PAPAIDDRVLIMITPERPERSON")
	private double pAPaidDrvLimitPerPerson;

}
