/*
*  Copyright (c) 2019. All right reserved
* Created on 2022-03-11 ( Date ISO 2022-03-11 - Time 16:18:38 )
* Generated by Telosys Tools Generator ( version 3.3.0 )
*/
package com.maan.crm.service.impl;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import com.maan.crm.repository.SessionDetailsRepository;
import com.maan.crm.bean.SessionDetails;
import com.maan.crm.service.SessionDetailsService;

import java.util.Collections;
import java.util.List;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
/**
* <h2>SessionDetailsServiceimpl</h2>
*/
@Service
@Transactional
public class SessionDetailsServiceImpl implements SessionDetailsService {

@Autowired
private SessionDetailsRepository repository;


private Logger log=LogManager.getLogger(SessionDetailsServiceImpl.class);
/*
public SessionDetailsServiceImpl(SessionDetailsRepository repo) {
this.repository = repo;
}

  */
 @Override
    public SessionDetails create(SessionDetails d) {

       SessionDetails entity;

        try {
            entity = repository.save(d);

        } catch (Exception ex) {
			log.error(ex);
            return null;
        }
        return entity;
    }

    
    @Override
    public SessionDetails update(SessionDetails d) {
        SessionDetails c;

        try {
            c = repository.saveAndFlush(d);

        } catch (Exception ex) {
			log.error(ex);
            return null;
        }
        return c;
    }

/*
    @Override
    public SessionDetails getOne(long id) {
        SessionDetails t;

        try {
            t = repository.findById(id).orElse(null);

        } catch (Exception ex) {
			log.error(ex);
            return null;
        }
        return t;
    }

*/
    @Override
    public List<SessionDetails> getAll() {
        List<SessionDetails> lst;

        try {
            lst = repository.findAll();

        } catch (Exception ex) {
			log.error(ex);
            return Collections.emptyList();
        }
        return lst;
    }


    @Override
    public long getTotal() {
        long total;

        try {
            total = repository.count();
        } catch (Exception ex) {
            log.error(ex);
			return 0;
        }
        return total;
    }

/*
    @Override
    public boolean delete(long id) {
        try {
            repository.deleteById(id);
            return true;

        } catch (Exception ex) {
			log.error(ex);
            return false;
        }
    }

 */

}
