/* 
*  Copyright (c) 2019. All right reserved
 * Created on 2022-05-14 ( Date ISO 2022-05-14 - Time 15:00:24 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
 * Created on 2022-05-14 ( 15:00:24 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */

package com.maan.crm.req;

import java.io.Serializable;

import com.fasterxml.jackson.annotation.JsonProperty;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * Domain class for entity "ClaimLoginUserDetails"
 *
 * @author Telosys Tools Generator
 *
 */
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor

public class ProspectQuotationPolicyAccountsSaveReq implements Serializable {

	private static final long serialVersionUID = 1L;

	// --- ENTITY PRIMARY KEY
	@JsonProperty("policyAccId")
	private int policyAccId;
	@JsonProperty("ProspectId")
	private int ProspectId;
	@JsonProperty("sumInsured")
	private double sumInsured;
	@JsonProperty("ownDamagePremium")
	private double ownDamagePremium;
	@JsonProperty("discountPercentage")
	private double discountPercentage;
	@JsonProperty("noClaimBonus")
	private double noClaimBonus;
	@JsonProperty("totalOwnDamagePremiumA")
	private double totalOwnDamagePremiumA;
	@JsonProperty("totalAddOnCoverPremiumB")
	private double totalAddOnCoverPremiumB;
	@JsonProperty("oDAddOnCommissionBasePremiumAB")
	private double oDAddOnCommissionBasePremiumAB;
	@JsonProperty("basicTP")
	private double basicTP;
	@JsonProperty("ownerDriverPAYN")
	private String ownerDriverPAYN;
	@JsonProperty("bifuelkitYN")
	private String bifuelkitYN;
	@JsonProperty("geographicalAreaYN")
	private String geographicalAreaYN;
	@JsonProperty("ownerDriverPA")
	private double ownerDriverPA;
	@JsonProperty("bifuelkit")
	private double bifuelkit;
	@JsonProperty("geographicalArea")
	private double geographicalArea;
	@JsonProperty("unnamedPassengerPAYN")
	private double unnamedPassengerPAYN;
	@JsonProperty("unnamedPassengerPA")
	private double unnamedPassengerPA;
	@JsonProperty("unnamedPassengerLimitPerPerson")
	private double unnamedPassengerLimitPerPerson;
	@JsonProperty("unnamedPassengerNoofSeats")
	private int unnamedPassengerNoofSeats;
	@JsonProperty("lLtoPaidDrvEmp")
	private double lLtoPaidDrvEmp;
	@JsonProperty("lLtoPaidDrvEmpYN")
	private String lLtoPaidDrvEmpYN;
	@JsonProperty("noofDrvEmp")
	private int noofDrvEmp;
	@JsonProperty("totalLiabilityPremiumC")
	private double totalLiabilityPremiumC;
	@JsonProperty("totalPremiumABC")
	private double totalPremiumABC;
	@JsonProperty("gST")
	private double gST;
	@JsonProperty("premiumwithGST")
	private double premiumwithGST;
	@JsonProperty("otherPremium")
	private double otherPremium;
	@JsonProperty("commissionBasePremium")
	private double commissionBasePremium;
	@JsonProperty("pAPaidDrv")
	private double pAPaidDrv;
	@JsonProperty("pAPaidDrvYN")
	private String pAPaidDrvYN;
	@JsonProperty("pAPaidDrvNoofSeats")
	private int pAPaidDrvNoofSeats;
	@JsonProperty("pAPaidDrvLimitPerPerson")
	private double pAPaidDrvLimitPerPerson;

}
