/* 
*  Copyright (c) 2019. All right reserved
 * Created on 2022-05-14 ( Date ISO 2022-05-14 - Time 15:00:24 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
 * Created on 2022-05-14 ( 15:00:24 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */

package com.maan.crm.req;

import java.io.Serializable;
import java.util.Date;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonProperty;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * Domain class for entity "ClaimLoginUserDetails"
 *
 * @author Telosys Tools Generator
 *
 */
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor

public class ProspectOldPolicyDetailsSaveReq implements Serializable {

	private static final long serialVersionUID = 1L;

	// --- ENTITY PRIMARY KEY
	@JsonProperty("ProspectId")
	private int prospectId;
	@JsonProperty("OldPolicyId")
	private int oldPolicyId;
	@JsonProperty("OldPolicyNo")
	private String oldPolicyNo;
	@JsonProperty("OldInsurer")
	private String oldInsurer;
	@JsonProperty("OldInsurerId")
	private int oldInsurerId;
	@JsonProperty("OldInsurancePlan")
	private String oldInsurancePlan;
	@JsonProperty("OldPOS")
	private String oldPOS;
	@JsonProperty("OldPOSId")
	private int oldPOSId;
	@JsonProperty("OldSource")
	private String oldSource;
	@JsonProperty("OldSourceId")
	private int oldSourceId;
	@JsonFormat(pattern = "dd/MM/yyyy")
	@JsonProperty("OldStartDate")
	private Date oldStartDate;
	@JsonFormat(pattern = "dd/MM/yyyy")
	@JsonProperty("OldExpiryDate")
	private Date oldExpiryDate;
	@JsonProperty("AnyClaimLastYear")
	private String anyClaimLastYear;
	@JsonProperty("AnyClaimLastYearId")
	private int anyClaimLastYearId;
	@JsonProperty("VehicleTransferCase")
	private String vehicleTransferCase;
	@JsonProperty("VehicleTransferCaseId")
	private int vehicleTransferCaseId;
	@JsonProperty("OldIDV")
	private String oldIDV;
	@JsonProperty("OldPolicyTerm")
	private String oldPolicyTerm;
	@JsonProperty("OldElectronicAccessoryValue")
	private String oldElectronicAccessoryValue;
	@JsonProperty("OldNonElectronicAccessoryValue")
	private String oldNonElectronicAccessoryValue;
	@JsonProperty("OldSumInsured")
	private double oldSumInsured;
	@JsonProperty("OldNoClaimBonus")
	private double oldNoClaimBonus;
	@JsonProperty("OldDiscountPercentage")
	private double oldDiscountPercentage;
	@JsonProperty("OldOwnDamagePremium")
	private double oldOwnDamagePremium;
	@JsonProperty("OldAddOnPremium")
	private double oldAddOnPremium;
	@JsonProperty("OldODAddOnCommissionBasePremium")
	private double oldODAddOnCommissionBasePremium;
	@JsonProperty("OldThirdPartyLiabilityPremium")
	private double oldThirdPartyLiabilityPremium;
	@JsonProperty("OldTotalPremium")
	private double oldTotalPremium;
	@JsonProperty("OldGST")
	private double oldGST;
	@JsonProperty("OldTotalPremiumwithGST")
	private double oldTotalPremiumwithGST;
	@JsonProperty("OldPolicyAdditionalInformation")
	private double oldPolicyAdditionalInformation;

}
