/* 
*  Copyright (c) 2019. All right reserved
 * Created on 2022-05-14 ( Date ISO 2022-05-14 - Time 15:00:24 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
 * Created on 2022-05-14 ( 15:00:24 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */

package com.maan.crm.req;

import java.io.Serializable;
import java.util.Date;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonProperty;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * Domain class for entity "ClaimLoginUserDetails"
 *
 * @author Telosys Tools Generator
 *
 */
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor

public class ProspectsQuotationOtherDetailsSaveReq implements Serializable {

	private static final long serialVersionUID = 1L;

	@JsonProperty("ProspectId")
	private int prospectId;
	
	@JsonProperty("OtherDetailsId")
	private int otherDetailsId;
	
	@JsonProperty("PolicyAdditionalInformation")
	private String policyAdditionalInformation;
	
	@JsonProperty("IssuedByUser")
	private String issuedByUser;
	
	@JsonProperty("RenewalNoticeFlagYN")
	private String renewalNoticeFlagYN;
	
	@JsonProperty("RecommendedFlagYN")
	private String recommendedFlagYN;
	
	@JsonFormat(pattern = "dd/MM/yyyy")
	@JsonProperty("IssueDate")
	private Date issueDate;

}
