/* 
*  Copyright (c) 2019. All right reserved
 * Created on 2022-01-05 ( Date ISO 2022-01-05 - Time 16:10:40 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
 * Created on 2022-01-05 ( 16:10:40 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */

package com.maan.crm.res;

import java.io.Serializable;
import java.util.Date;

import com.fasterxml.jackson.annotation.JsonProperty;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class CompanyTypeMasterRes implements Serializable {

	private static final long serialVersionUID = 1L;

	@JsonProperty("Sno")
	private Integer sNo;

	@JsonProperty("InsCompanyId")
	private String insCompanyId;

	@JsonProperty("CompanyType")
	private String companyType;

	@JsonProperty("Status")
	private String status;

	@JsonProperty("EntryDate")
	private Date entryDate;

	@JsonProperty("Remarks")
	private String remarks;

}
