/*
*  Copyright (c) 2019. All right reserved
* Created on 2022-03-11 ( Date ISO 2022-03-11 - Time 16:18:38 )
* Generated by Telosys Tools Generator ( version 3.3.0 )
*/
package com.maan.crm.service;
import com.maan.crm.bean.SessionDetails;

import java.util.List;
/**
* <h2>SessionDetailsServiceimpl</h2>
*/
public interface SessionDetailsService  {

SessionDetails create(SessionDetails d);
SessionDetails update(SessionDetails d);
//SessionDetails getOne(long id) ;
 List<SessionDetails> getAll();
long getTotal();
//boolean delete(long id);

}
