/*
 * Java domain class for entity "ClaimLoginMaster" 
 * Created on 2022-05-14 ( Date ISO 2022-05-14 - Time 15:00:24 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
 
 /*
 * Created on 2022-05-14 ( 15:00:24 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.crm.repository;

import java.util.List;
import java.util.Optional;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;

import com.maan.crm.bean.ClaimLoginMaster;
import com.maan.crm.bean.ClaimLoginMasterId;
/**
 * <h2>ClaimLoginMasterRepository</h2>
 *
 * createdAt : 2022-05-14 - Time 15:00:24
 * <p>
 * Description: "ClaimLoginMaster" Repository
 */
 
 
 
public interface ClaimLoginMasterRepository  extends JpaRepository<ClaimLoginMaster,ClaimLoginMasterId> , JpaSpecificationExecutor<ClaimLoginMaster> {

	ClaimLoginMaster findByLoginIdAndPassword(String userId, String epass);

	ClaimLoginMaster findByLoginId(String createdBy);

	Optional<ClaimLoginMaster> findByLoginIdAndCompanyId(String userId, String companyId);

	ClaimLoginMaster findByAgencyCode(String agencyCode);

	ClaimLoginMaster findByLoginIdAndAgencyCode(String loginId, String agencyCode);
	
}
