/*
 * Java domain class for entity "SessionDetails" 
 * Created on 2021-08-13 ( Date ISO 2021-08-13 - Time 15:03:28 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
* Created on 2021-08-13 ( 15:03:28 )
* Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
*/

package com.maan.crm.repository;

import java.util.List;
import java.util.Map;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.jpa.repository.Query;
import org.springframework.stereotype.Repository;

import com.maan.crm.bean.UsertypeMaster;
import com.maan.crm.bean.UsertypeMasterId;

/**
 * <h2>SessionDetailsRepository</h2>
 *
 * createdAt : 2021-08-13 - Time 15:03:28
 * <p>
 * Description: "SessionDetails" Repository
 */

@Repository
public interface UserTypeMasterRepository extends JpaRepository<UsertypeMaster, UsertypeMasterId>, JpaSpecificationExecutor<UsertypeMaster> {

	List<UsertypeMaster> findByUsertypeDescriptionAndStatusOrderByUsertypeIdAsc(String usertypeDescription, String status);

	List<UsertypeMaster> findByCompanyIdOrderByEntryDate(String companyId);

	List<UsertypeMaster> findByStatusOrderByOrderIdAsc(String string);

	UsertypeMaster findByUsertypeDescription(String userType);

	Integer countByCompanyIdOrderByEntryDate(String companyId);

	List<UsertypeMaster> findByStatusOrderByUsertypeIdAsc(String string);
	
	@Query(nativeQuery=true ,value ="SELECT LOGIN_ID,AGENCY_CODE FROM login_master WHERE UPPER(usertype) = (SELECT DISTINCT UPPER(USERTYPE_DESCRIPTION) FROM USERTYPE_MASTER WHERE USERTYPE_ID=?1 AND STATUS='Y' AND COMPANY_ID='OMAN') AND STATUS='Y'")
	List<Map<String,Object>> getUserDetailsList(String userTypeId);




	
}
